services:
  web:
    image: danylovitkovskyi/tdist-lab-1:latest
    ports:
      - 80:80

  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.52
    command: --interval 30
