services:
  hello:
    container_name: trist_hello
    image: danylovitkovskyi/tdist-lab-4:latest
    working_dir: /app
    command: ./trist
    ports:
      - 80:8080
    networks:
      - fullstack

  prometheus:
    container_name: trist_prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    networks:
      - fullstack
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  grafana:
    container_name: trist_grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - fullstack
    volumes:
      # Mount the provisioning configs
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      # Mount the actual JSON dashboard files
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.52
    command: --interval 30

networks:
  fullstack:
    driver: bridge

volumes:
  prometheus-data:
